package edu.uic.cs.t_verifier.index;

public interface IndexConstants
{
	String FIELD_NAME__STATEMENT_ID = "STATEMENT_ID";

	String FIELD_NAME__STATEMENT_TYPE = "STATEMENT_TYPE";

	String FIELD_NAME__DOC_TYPE = "DOC_TYPE";
	String DOC_TYPE__STATEMENT_METADATA = "STATEMENT_METADATA";
	String DOC_TYPE__PAGE_CONTENT = "PAGE_CONTENT";

	String FIELD_NAME__ALL_TOPIC_UNIT_WORDS = "ALL_TOPIC_UNIT_WORDS";

	String FIELD_NAME__AlTERNATIVE_UNIT = "AlTERNATIVE_UNIT";
	String FIELD_NAME__PREFIX__AlTERNATIVE_UNIT_URLS = "AlTERNATIVE_UNIT_URLS__";

	String FIELD_NAME__MATCHED_SUB_TU = "MATCHED_SUB_TU";
	String FIELD_NAME__PREFIX__MATCHED_SUB_TU_URLS = "MATCHED_SUB_TU_URLS__";

	String FIELD_NAME__MATCHED_UNIT = "MATCHED_UNIT";
	String FIELD_NAME__CATEGORIES = "CATEGORIES";

	String FIELD_NAME__CONTENT_INDEXED_BY_SEGMENT = "CONTENT_INDEXED_BY_SEGMENT";
	String FIELD_NAME__CONTENT_INDEXED_BY_PARAGRAPH = "CONTENT_INDEXED_BY_PARAGRAPH";
	String FIELD_NAME__CONTENT_INDEXED_BY_SENTENCE = "CONTENT_INDEXED_BY_SENTENCE";
}
